#!/usr/bin/env python3
"""
Generate notebook 37 — full Multi-Probe DPO run on Qwen3.6-27B.

Lessons baked in from POC failures (nb35):
  - max_new_tokens=1024 (POC had 256, killed RG signal — 0% has_think rate)
  - 200 pairs (POC had 50, DPO loss flat at ln(2))
  - 100+ effective steps (POC had 10, weights moved 0.4% only)
  - LoRA save format verification + key-rename fix (POC bug: double `base_model.model.` prefix, missing `.default.`)
  - Anti-Goodhart fresh probe AUROC mandatory before claiming any effect
  - Drive checkpoints + HF incremental + per-phase resume markers
  - Hooks re-registered AFTER PEFT wrapping
  - torchao>=0.16.0 explicit pin
  - LoRA load sanity test (generate base vs student, abort if identical)
"""
import json
from pathlib import Path

NOTEBOOKS_DIR = Path('/Volumes/SSD Major/fish/openinterp-work/notebooks')
NOTEBOOKS_DIR.mkdir(parents=True, exist_ok=True)


def md(text):
    if isinstance(text, str):
        lines = text.rstrip('\n').split('\n')
    else:
        lines = list(text)
    return {'cell_type': 'markdown', 'metadata': {}, 'source': [l + '\n' for l in lines]}


def code(text):
    if isinstance(text, str):
        lines = text.rstrip('\n').split('\n')
    else:
        lines = list(text)
    return {'cell_type': 'code', 'metadata': {}, 'execution_count': None, 'outputs': [],
            'source': [l + '\n' for l in lines]}


def write_nb(cells, out):
    nb = {'cells': cells,
          'metadata': {'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
                       'language_info': {'name': 'python', 'version': '3.11'},
                       'colab': {'provenance': [], 'machine_shape': 'hm'},
                       'accelerator': 'GPU'},
          'nbformat': 4, 'nbformat_minor': 4}
    out.write_text(json.dumps(nb, indent=1, ensure_ascii=False))
    print(f'Wrote {out.name}  ({out.stat().st_size/1024:.1f} KB, {len(cells)} cells)')


def build_nb37():
    cells = []

    # ============================================================
    # HEADER
    # ============================================================
    cells.append(md([
        '# Multi-Probe DPO — Full Run on Qwen3.6-27B',
        '',
        '**Notebook 37 · OpenInterp · 2026-04-29**',
        '',
        'First OSS demonstration of multi-probe-reward DPO on a 27B+ open-weights LLM with anti-Goodhart fresh-probe validation. Direct extension of Goodfire RLFR (Apr 2026, single-probe, −58% halu) to multi-probe orthogonal-objective design.',
        '',
        '## What this notebook does',
        '',
        '1. **Phase 1-3** — Setup, load Qwen3.6-27B, register hooks, load probes',
        '2. **Phase 4-5** — Build 200 multi-probe DPO pairs (`max_new=1024` to capture `<think>` traces, REQUIRED for ReasonGuard signal)',
        '3. **Phase 6** — DPO training (100+ effective steps, KL-constrained)',
        '4. **Phase 7** — LoRA save with **explicit key-format verification** (POC had a save/load bug we fix here)',
        '5. **Phase 8** — Eval base vs student on 100 held-out queries',
        '6. **Phase 9** — **Anti-Goodhart fresh probe AUROC** — mandatory validation. If fresh probe AUROC ≥ 0.80, reduction is real; if < 0.65, evasion. Without this, no claim is defensible.',
        '7. **Phase 10** — Final verdict + plots + HF push',
        '',
        '## Lessons from POC nb35 (baked in here)',
        '',
        '| POC bug | Fix in nb37 |',
        '|---|---|',
        '| `max_new_tokens=256` → 0% has_think → RG silent | `max_new_tokens=1024` |',
        '| 50 pairs / 10 steps → loss flat at ln(2), 0.4% weight perturbation | 200 pairs / 100+ steps |',
        '| LoRA save with double `base_model.model.` prefix, missing `.default.` | Phase 7 verifies + auto-fixes save format |',
        '| Hooks registered before PEFT → stale | Hooks re-registered AFTER `get_peft_model` |',
        '| `mixed = []` overwritten between cells | All state in memory + Drive markers |',
        '| Eval delta from greedy boundary noise misread as learning | Anti-Goodhart fresh probe AUROC mandatory |',
        '',
        '## Compute budget',
        '',
        '- 1× RTX PRO 6000 96GB or H100 80GB',
        '- Wall-clock: **~10-11h end-to-end**',
        '- Cost: ~R$45 Colab Pro+ credits or ~$15 vast.ai H100 PCIe',
        '',
        '## Outputs',
        '',
        'Drive: `/content/drive/MyDrive/openinterp_runs/37_multiprobe_dpo_full/`',
        'HF: `caiovicentino1/openinterp-37-multiprobe-dpo-full`',
        '',
        'Files: pairs.json, lora_final/ (verified format), eval_results.csv, fresh_activations_*.npz, antigoodhart_verdict.json, plots/',
    ]))

    # ============================================================
    # PHASE 1 — Setup
    # ============================================================
    cells.append(md([
        '## Phase 1 — Drive mount + checkpoint dir (NON-NEGOTIABLE)',
        '',
        'Drive mount mandatory. /content/ alone is volatile — Colab disconnects = 10h lost.',
    ]))
    cells.append(code([
        '# === DRIVE MOUNT — non-negotiable ===',
        'from pathlib import Path',
        'import os, sys, time',
        '',
        'try:',
        '    from google.colab import drive',
        '    drive.mount("/content/drive", force_remount=False)',
        'except Exception as e:',
        '    print(f"Drive mount FAILED: {e}"); raise',
        '',
        'DRIVE_ROOT = Path("/content/drive/MyDrive")',
        'assert DRIVE_ROOT.exists(), "Drive mount silently failed"',
        'NB_NAME = "37_multiprobe_dpo_full"',
        'OUT = DRIVE_ROOT / "openinterp_runs" / NB_NAME',
        'OUT.mkdir(parents=True, exist_ok=True)',
        '(OUT / "_dry_run.txt").write_text("drive mount OK")',
        'print(f"✓ Drive checkpoint dir: {OUT}")',
        'print(f"  Existing artifacts: {sorted(p.name for p in OUT.iterdir())}")',
    ]))

    cells.append(code([
        '!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader || echo "no GPU"',
    ]))

    cells.append(md(['## Phase 1.5 — Install dependencies (with critical version pins)']))
    cells.append(code([
        '# torchao>=0.16.0 MANDATORY before peft import (POC bug)',
        '%pip install -q -U torchao',
        '%pip install -q -U transformers accelerate peft trl datasets safetensors huggingface_hub',
        '%pip install -q -U scikit-learn matplotlib seaborn joblib sentencepiece protobuf tqdm',
        'print("✓ Dependencies installed")',
        'print("  IMPORTANT: if peft import fails on next cell, RESTART runtime then run all again")',
    ]))

    cells.append(code([
        'import os, json, time, math, gc, re',
        'from pathlib import Path',
        'from typing import Optional, Tuple, List, Dict',
        'import numpy as np, pandas as pd',
        'import torch',
        'import torch.nn.functional as F',
        'from tqdm.auto import tqdm',
        'import joblib',
        'from huggingface_hub import login, hf_hub_download, snapshot_download, HfApi, create_repo',
        'from datasets import load_dataset, Dataset',
        'from sklearn.linear_model import LogisticRegressionCV',
        'from sklearn.preprocessing import StandardScaler',
        'from sklearn.model_selection import train_test_split',
        'from sklearn.metrics import roc_auc_score',
        'import matplotlib.pyplot as plt',
        '',
        'CFG = {',
        '    "model":            "Qwen/Qwen3.6-27B",',
        '    "fg_repo":          "caiovicentino1/FabricationGuard-linearprobe-qwen36-27b",',
        '    "rg_repo":          "caiovicentino1/ReasoningGuard-linearprobe-qwen36-27b",',
        '    "fg_layer":         31,',
        '    "rg_layer":         55,',
        '    "probe_layers":     [31, 55],',
        '    # ============ Lessons from POC ============',
        '    "max_new_tokens":   1024,    # POC=256 killed RG signal',
        '    "build_n_simpleqa": 100,     # POC had 25 → tiny',
        '    "build_n_gsm8k":    100,',
        '    "cands_per_q":      4,',
        '    "eval_n_simpleqa":  50,',
        '    "eval_n_gsm8k":     50,',
        '    "antigoodhart_n_simpleqa": 80,',
        '    "antigoodhart_n_gsm8k":    80,',
        '    "reward_alpha":     [0.5, 0.5],   # FG, RG weights',
        '    # ============ DPO training ============',
        '    "num_train_epochs": 2,           # 200 pairs × 2 epochs / (batch 1 × grad_accum 4) = 100 effective steps',
        '    "lora_r":           16,',
        '    "lora_alpha":       32,',
        '    "dpo_lr":           5e-6,',
        '    "dpo_beta":         0.1,',
        '    "save_steps":       20,',
        '    # ============ Repro / output ============',
        '    "random_seed":      42,',
        '    "output_repo":      "caiovicentino1/openinterp-37-multiprobe-dpo-full",',
        '}',
        'THINK_OPEN_ID  = 248068',
        'THINK_CLOSE_ID = 248069',
        '',
        'torch.manual_seed(CFG["random_seed"]); np.random.seed(CFG["random_seed"])',
        'import random; random.seed(CFG["random_seed"])',
        '',
        'HF_TOKEN = os.environ.get("HF_TOKEN")',
        'if HF_TOKEN is None:',
        '    import getpass; HF_TOKEN = getpass.getpass("HF token (write scope): ")',
        'login(HF_TOKEN, add_to_git_credential=False)',
        '',
        'try:',
        '    create_repo(CFG["output_repo"], repo_type="dataset", private=False, exist_ok=True, token=HF_TOKEN)',
        '    print(f"✓ HF repo ready: {CFG[\'output_repo\']}")',
        'except Exception as e:',
        '    print(f"create_repo: {e}")',
        '',
        'device = "cuda"; assert torch.cuda.is_available()',
        'gpu_mem_gb = torch.cuda.get_device_properties(0).total_memory / 1e9',
        'print(f"✓ {torch.cuda.get_device_name(0)}, {gpu_mem_gb:.1f} GB")',
        'assert gpu_mem_gb >= 60, "Need ≥60 GB VRAM for Qwen3.6-27B BF16 + LoRA + KV cache"',
        '',
        '(OUT / "_setup_done.txt").write_text(json.dumps({"ts": time.time(), "gpu": torch.cuda.get_device_name(0)}, indent=2))',
        'print("✓ Phase 1 complete — _setup_done.txt saved")',
    ]))

    # ============================================================
    # PHASE 2 — Load model + LoRA + hooks
    # ============================================================
    cells.append(md(['## Phase 2 — Load Qwen3.6-27B + apply LoRA + register hooks AFTER PEFT']))
    cells.append(code([
        'from transformers import AutoTokenizer, AutoModelForImageTextToText, AutoModelForCausalLM',
        'from peft import LoraConfig, get_peft_model, TaskType',
        '',
        'print(f"Loading {CFG[\'model\']} ...")',
        't0 = time.time()',
        'tok = AutoTokenizer.from_pretrained(CFG["model"], trust_remote_code=True)',
        'try:',
        '    model = AutoModelForImageTextToText.from_pretrained(',
        '        CFG["model"], dtype=torch.bfloat16, attn_implementation="sdpa",',
        '        device_map={"":device}, trust_remote_code=True)',
        '    print("  loaded as ImageTextToText")',
        'except Exception as e:',
        '    print(f"  ImageTextToText failed ({type(e).__name__}); fallback to CausalLM")',
        '    model = AutoModelForCausalLM.from_pretrained(',
        '        CFG["model"], dtype=torch.bfloat16, attn_implementation="sdpa",',
        '        device_map={"":device}, trust_remote_code=True)',
        'model.eval()',
        'for p in model.parameters(): p.requires_grad_(False)',
        'print(f"✓ Base loaded in {time.time()-t0:.0f}s, {torch.cuda.memory_allocated()/1e9:.1f} GB")',
        '',
        '# Apply LoRA',
        'lora_cfg = LoraConfig(',
        '    r=CFG["lora_r"], lora_alpha=CFG["lora_alpha"], lora_dropout=0.05,',
        '    target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],',
        '    task_type=TaskType.CAUSAL_LM, bias="none",',
        ')',
        'model = get_peft_model(model, lora_cfg)',
        'model.print_trainable_parameters()',
        '',
        '# Find blocks AFTER PEFT wrapping (POC bug: pre-PEFT hooks become stale)',
        'def _block_list_peft(m):',
        '    candidates = [m]',
        '    for attr in ["base_model", "model"]:',
        '        if hasattr(m, attr): candidates.append(getattr(m, attr))',
        '    if hasattr(m, "base_model") and hasattr(m.base_model, "model"):',
        '        candidates.append(m.base_model.model)',
        '        if hasattr(m.base_model.model, "model"):',
        '            candidates.append(m.base_model.model.model)',
        '    for s in candidates:',
        '        if s is None: continue',
        '        for path in [("model","language_model","layers"),("language_model","layers"),("model","layers"),("layers",)]:',
        '            cur=s; ok=True',
        '            for p in path:',
        '                if hasattr(cur,p): cur=getattr(cur,p)',
        '                else: ok=False; break',
        '            if ok and hasattr(cur,"__getitem__") and hasattr(cur,"__len__") and len(cur) > 50:',
        '                return cur',
        '    raise RuntimeError("layers not found")',
        '',
        'blocks = _block_list_peft(model)',
        'print(f"✓ Found {len(blocks)} layers")',
        '',
        '# Register hooks at L31, L55',
        'class MultiLayerHook:',
        '    def __init__(self, blocks, layers):',
        '        self.bufs = {l:None for l in layers}; self.handles=[]',
        '        for l in layers:',
        '            self.handles.append(blocks[l].register_forward_hook(self._make(l)))',
        '    def _make(self, l):',
        '        def hook(_m,_i,out):',
        '            h = out[0] if isinstance(out,tuple) else out',
        '            self.bufs[l] = h.detach()',
        '        return hook',
        '    def pop(self, l):',
        '        b = self.bufs[l]; self.bufs[l]=None; return b',
        '    def close(self):',
        '        for h in self.handles: h.remove()',
        '',
        'ml_hook = MultiLayerHook(blocks, CFG["probe_layers"])',
        'print(f"✓ Hooks registered at L{CFG[\'probe_layers\']}")',
        '',
        '# SANITY: forward must populate buffers',
        'with torch.no_grad():',
        '    test_enc = tok("test sanity", return_tensors="pt").to(device)',
        '    with model.disable_adapter():',
        '        _ = model(**test_enc)',
        'ok31 = ml_hook.bufs[31] is not None',
        'ok55 = ml_hook.bufs[55] is not None',
        'print(f"  L31 hook fires: {ok31}, L55 hook fires: {ok55}")',
        'assert ok31 and ok55, "Hooks not firing — abort"',
        'ml_hook.pop(31); ml_hook.pop(55)',
        '',
        '(OUT / "_phase2_done.txt").write_text(f"ts={time.time()}, vram={torch.cuda.memory_allocated()/1e9:.1f} GB")',
        'print("✓ Phase 2 complete")',
    ]))

    # ============================================================
    # PHASE 3 — Load probes
    # ============================================================
    cells.append(md(['## Phase 3 — Load FabricationGuard + ReasonGuard probes']))
    cells.append(code([
        'def load_probe_bundle(repo, fname="probe.joblib"):',
        '    p = hf_hub_download(repo, repo_type="dataset", filename=fname)',
        '    obj = joblib.load(p)',
        '    return obj["probe"], obj["scaler"]',
        '',
        'fg_probe, fg_scaler = load_probe_bundle(CFG["fg_repo"])',
        'rg_probe, rg_scaler = load_probe_bundle(CFG["rg_repo"])',
        'print(f"✓ FG probe loaded (L{CFG[\'fg_layer\']}/end_question)")',
        'print(f"✓ RG probe loaded (L{CFG[\'rg_layer\']}/mid_think)")',
        '',
        '(OUT / "_phase3_done.txt").write_text(f"ts={time.time()}")',
    ]))

    # ============================================================
    # PHASE 4 — Helpers
    # ============================================================
    cells.append(md(['## Phase 4 — Multi-probe scoring + generation helpers']))
    cells.append(code([
        '@torch.no_grad()',
        'def fg_score(question: str, answer: str) -> float:',
        '    """L31 at end of `Q: ... \\nA: ...` prompt — FabricationGuard signal."""',
        '    prompt = f"Q: {question}\\nA: {answer}"',
        '    enc = tok(prompt, return_tensors="pt", truncation=True, max_length=2048).to(device)',
        '    n = int(enc["attention_mask"].sum().item())',
        '    with model.disable_adapter():',
        '        _ = model(**enc)',
        '    h = ml_hook.pop(CFG["fg_layer"])[0, n-1].float().cpu().numpy()',
        '    return float(fg_probe.predict_proba(fg_scaler.transform([h]))[0, list(fg_probe.classes_).index(1)])',
        '',
        '@torch.no_grad()',
        'def rg_score(question: str, full_answer: str) -> Optional[float]:',
        '    """L55 at midpoint of <think>...</think> — ReasonGuard signal. None if no thinking trace."""',
        '    chat = [{"role":"user","content":question}]',
        '    prefix = tok.apply_chat_template(chat, tokenize=False,',
        '                                     add_generation_prompt=True, enable_thinking=True)',
        '    enc = tok(prefix + full_answer, return_tensors="pt", truncation=True, max_length=4096).to(device)',
        '    ids = enc["input_ids"][0].tolist()',
        '    op = next((i for i,t in enumerate(ids) if t == THINK_OPEN_ID), None)',
        '    cl = next((i for i,t in enumerate(ids) if t == THINK_CLOSE_ID), None)',
        '    if op is None or cl is None or cl <= op + 5:',
        '        return None',
        '    mid = (op + cl) // 2',
        '    with model.disable_adapter():',
        '        _ = model(**enc)',
        '    h = ml_hook.pop(CFG["rg_layer"])[0, mid].float().cpu().numpy()',
        '    return float(rg_probe.predict_proba(rg_scaler.transform([h]))[0, list(rg_probe.classes_).index(1)])',
        '',
        'def combined_reward(q: str, a: str):',
        '    """Multi-probe reward. Falls back to FG-only when no thinking trace."""',
        '    fg = fg_score(q, a)',
        '    rg = rg_score(q, a)',
        '    if rg is not None:',
        '        comb = CFG["reward_alpha"][0]*fg + CFG["reward_alpha"][1]*rg',
        '    else:',
        '        comb = fg',
        '    return {"fg": fg, "rg": rg, "combined": comb, "reward": -comb, "has_think": rg is not None}',
        '',
        '@torch.no_grad()',
        'def gen_one(question: str, temp: float = 0.7, max_new: int = None) -> str:',
        '    if max_new is None: max_new = CFG["max_new_tokens"]',
        '    msgs = [{"role":"user","content":question}]',
        '    txt = tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True, enable_thinking=True)',
        '    enc = tok(txt, return_tensors="pt").to(device)',
        '    out = model.generate(**enc, max_new_tokens=max_new, do_sample=(temp>0),',
        '                         temperature=temp if temp>0 else 1.0, top_p=0.9,',
        '                         pad_token_id=tok.pad_token_id or tok.eos_token_id)',
        '    return tok.decode(out[0, enc["input_ids"].shape[1]:], skip_special_tokens=True).strip()',
        '',
        '# SANITY check: probe scores reasonable on known prompts',
        'sanity_known   = "What is the capital of France?"',
        'sanity_unknown = "Who won the 2003 Nobel Prize in Aerodynamics?"  # fake category',
        's_known = fg_score(sanity_known, "Paris")',
        's_unknown = fg_score(sanity_unknown, "Dr. Roger Smith of MIT")',
        'print(f"  FG sanity: known={s_known:.3f}, unknown={s_unknown:.3f}")',
        'assert s_unknown > s_known, f"Probe sanity fail — unknown should score higher than known"',
        'print("✓ Phase 4 complete (helpers ready)")',
    ]))

    # ============================================================
    # PHASE 5 — Build DPO pairs
    # ============================================================
    cells.append(md([
        '## Phase 5 — Build 200 multi-probe DPO pairs (~6h with max_new=1024)',
        '',
        'Resumable: reads existing `pairs_partial.json` and continues from where last run left off.',
        '',
        'Each iteration: 4 candidates × generation + 2 probes × scoring = ~110s wall-clock.',
    ]))
    cells.append(code([
        '# Build mixed corpus',
        'sqa = load_dataset("basicv8vc/SimpleQA", split="test").shuffle(seed=42).select(range(CFG["build_n_simpleqa"]))',
        'gsm = load_dataset("openai/gsm8k", "main", split="test").shuffle(seed=42).select(range(CFG["build_n_gsm8k"]))',
        '',
        'mixed = []',
        'for i in range(CFG["build_n_simpleqa"]): mixed.append({"q": sqa[i]["problem"],  "src": "simpleqa", "id": f"sqa_{i}"})',
        'for i in range(CFG["build_n_gsm8k"]):    mixed.append({"q": gsm[i]["question"], "src": "gsm8k",    "id": f"gsm_{i}"})',
        'np.random.default_rng(42).shuffle(mixed)',
        'print(f"Mixed corpus: {len(mixed)} questions")',
        'assert len(mixed) == CFG["build_n_simpleqa"] + CFG["build_n_gsm8k"]',
    ]))
    cells.append(code([
        '# Resume support',
        'pairs_path = OUT / "pairs.json"',
        'tele_path  = OUT / "pair_telemetry.csv"',
        '',
        'if pairs_path.exists() and tele_path.exists():',
        '    pairs = json.loads(pairs_path.read_text())',
        '    df_t  = pd.read_csv(tele_path)',
        '    done_ids = set(df_t["id"].tolist()) if "id" in df_t.columns else set()',
        '    print(f"✓ Resume: {len(pairs)} pairs already built ({len(done_ids)} unique IDs)")',
        'else:',
        '    pairs = []',
        '    df_t = pd.DataFrame()',
        '    done_ids = set()',
        '    print("Starting fresh")',
        '',
        'remaining = [m for m in mixed if m["id"] not in done_ids]',
        'print(f"  Remaining: {len(remaining)}/{len(mixed)}")',
        '',
        'api = HfApi()',
        '',
        '# The build loop',
        'pbar = tqdm(remaining, desc="build pairs")',
        'for ex in pbar:',
        '    q = ex["q"]',
        '    cands = [gen_one(q, temp=0.7) for _ in range(CFG["cands_per_q"])]',
        '    rs = [combined_reward(q, c) for c in cands]',
        '    best_i  = int(np.argmin([r["combined"] for r in rs]))',
        '    worst_i = int(np.argmax([r["combined"] for r in rs]))',
        '    pairs.append({',
        '        "id": ex["id"], "src": ex["src"],',
        '        "prompt": q, "chosen": cands[best_i], "rejected": cands[worst_i]',
        '    })',
        '    new_row = {',
        '        "id": ex["id"], "src": ex["src"], "q": q[:120],',
        '        "fg_best": rs[best_i]["fg"], "fg_worst": rs[worst_i]["fg"],',
        '        "rg_best": rs[best_i]["rg"], "rg_worst": rs[worst_i]["rg"],',
        '        "combined_gap": rs[worst_i]["combined"] - rs[best_i]["combined"],',
        '        "has_think_rate": sum(1 for r in rs if r["has_think"]) / len(rs),',
        '    }',
        '    df_t = pd.concat([df_t, pd.DataFrame([new_row])], ignore_index=True)',
        '    pbar.set_postfix(gap=f"{new_row[\'combined_gap\']:.3f}", think=f"{new_row[\'has_think_rate\']:.2f}")',
        '',
        '    # Drive checkpoint every 10',
        '    if len(pairs) % 10 == 0:',
        '        pairs_path.write_text(json.dumps(pairs, indent=2))',
        '        df_t.to_csv(tele_path, index=False)',
        '    # HF push every 50',
        '    if len(pairs) % 50 == 0:',
        '        try:',
        '            api.upload_folder(folder_path=str(OUT), repo_id=CFG["output_repo"],',
        '                              repo_type="dataset", token=HF_TOKEN,',
        '                              commit_message=f"build pairs partial @ {len(pairs)}",',
        '                              allow_patterns=["pairs.json", "pair_telemetry.csv"])',
        '        except Exception as e:',
        '            print(f"  HF push failed (continue): {type(e).__name__}: {str(e)[:80]}")',
        '',
        '# Final save',
        'pairs_path.write_text(json.dumps(pairs, indent=2))',
        'df_t.to_csv(tele_path, index=False)',
        '',
        'print(f"\\n=== Build pairs complete: {len(pairs)} pairs ===")',
        'print(f"Mean combined_gap: {df_t[\'combined_gap\'].mean():.3f}")',
        'print(f"Mean has_think_rate: {df_t[\'has_think_rate\'].mean():.2f}")',
        'print(df_t.groupby("src")[["combined_gap","has_think_rate"]].mean())',
        '',
        'df_both = df_t.dropna(subset=["rg_best"])',
        'if len(df_both) > 5:',
        '    rho = np.corrcoef(df_both["fg_best"], df_both["rg_best"])[0,1]',
        '    print(f"\\nFG-RG Pearson (orthogonality test): {rho:+.3f}  ({\'orthogonal ✅\' if abs(rho)<0.4 else \'correlated ⚠️\'})")',
        '',
        'api.upload_folder(folder_path=str(OUT), repo_id=CFG["output_repo"],',
        '                  repo_type="dataset", token=HF_TOKEN,',
        '                  commit_message=f"Phase 5 complete: {len(pairs)} pairs built",',
        '                  allow_patterns=["pairs.json", "pair_telemetry.csv"])',
        '(OUT / "_phase5_done.txt").write_text(f"ts={time.time()}, n_pairs={len(pairs)}")',
        'print("✓ Phase 5 complete")',
    ]))

    # ============================================================
    # PHASE 6 — DPO training
    # ============================================================
    cells.append(md(['## Phase 6 — DPO training (~30-60 min)']))
    cells.append(code([
        'from trl import DPOTrainer, DPOConfig',
        '',
        '# Load pairs',
        'pairs = json.loads((OUT / "pairs.json").read_text())',
        'print(f"Loaded {len(pairs)} pairs")',
        '',
        '# Train/test split inside the trainer (80/20)',
        'ds = Dataset.from_list(pairs).train_test_split(test_size=0.2, seed=CFG["random_seed"])',
        'print(f"  Train: {len(ds[\'train\'])}, Eval: {len(ds[\'test\'])}")',
        '',
        'dpo_cfg = DPOConfig(',
        '    output_dir=str(OUT / "dpo_run"),',
        '    num_train_epochs=CFG["num_train_epochs"],',
        '    per_device_train_batch_size=1,',
        '    gradient_accumulation_steps=4,',
        '    learning_rate=CFG["dpo_lr"],',
        '    beta=CFG["dpo_beta"],',
        '    save_steps=CFG["save_steps"],',
        '    logging_steps=2,',
        '    bf16=True,',
        '    report_to="none",',
        '    save_strategy="steps",',
        '    save_total_limit=3,',
        ')',
        '',
        'trainer = DPOTrainer(',
        '    model=model, args=dpo_cfg,',
        '    train_dataset=ds["train"], eval_dataset=ds["test"],',
        '    processing_class=tok,',
        ')',
        'trainer.train()',
        '',
        '# Save state to Drive (this is the canonical PEFT save)',
        'model.save_pretrained(str(OUT / "lora_final"))',
        'tok.save_pretrained(str(OUT / "lora_final"))',
        'print(f"✓ LoRA saved to {OUT / \'lora_final\'}")',
        '',
        '(OUT / "_phase6_done.txt").write_text(f"ts={time.time()}, final_loss={trainer.state.log_history[-1].get(\'loss\', \'?\')}")',
        '# Push training artifacts',
        'api.upload_folder(folder_path=str(OUT), repo_id=CFG["output_repo"],',
        '                  repo_type="dataset", token=HF_TOKEN,',
        '                  commit_message="Phase 6 complete: DPO trained",',
        '                  allow_patterns=["lora_final/*", "dpo_run/**", "_phase6_done.txt"])',
        'print("✓ Phase 6 complete")',
    ]))

    # ============================================================
    # PHASE 7 — Verify LoRA save format + sanity reload test
    # ============================================================
    cells.append(md([
        '## Phase 7 — Verify LoRA save format + sanity reload test',
        '',
        '**This phase prevents the POC bug**: TRL/PEFT can save adapter with broken key naming (double `base_model.model.` prefix, missing `.default.`). We verify and auto-fix here.',
    ]))
    cells.append(code([
        'from safetensors.torch import load_file, save_file',
        '',
        'adapter_path = OUT / "lora_final" / "adapter_model.safetensors"',
        'saved = load_file(str(adapter_path))',
        'sample_key = next(iter(saved))',
        'print(f"Sample key: {sample_key}")',
        '',
        'broken_double_prefix = sample_key.count("base_model.model.") > 1',
        'broken_no_default = sample_key.endswith(".lora_A.weight") or sample_key.endswith(".lora_B.weight")',
        '',
        'if broken_double_prefix or broken_no_default:',
        '    print(f"⚠️  Detected POC-style bug: double_prefix={broken_double_prefix}, no_default={broken_no_default}")',
        '    fixed = {}',
        '    for k, v in saved.items():',
        '        nk = k',
        '        if nk.startswith("base_model.model.base_model.model."):',
        '            nk = "base_model.model." + nk[len("base_model.model.base_model.model."):]',
        '        if nk.endswith(".lora_A.weight"):',
        '            nk = nk[:-len(".weight")] + ".default.weight"',
        '        elif nk.endswith(".lora_B.weight"):',
        '            nk = nk[:-len(".weight")] + ".default.weight"',
        '        fixed[nk] = v',
        '    save_file(fixed, str(adapter_path))',
        '    print(f"✓ Fixed adapter format: {len(fixed)} keys, sample: {next(iter(fixed))}")',
        '    saved = fixed',
        'else:',
        '    print("✓ Save format OK (no fix needed)")',
        '',
        '# Compute lora_B.norm — must be > 1e-3 if real training happened',
        'lora_b_norms = [v.float().norm().item() for k, v in saved.items() if "lora_B" in k]',
        'print(f"  lora_B norms: mean={np.mean(lora_b_norms):.5f}, max={max(lora_b_norms):.5f}, n_zero={sum(1 for n in lora_b_norms if n < 1e-6)}/{len(lora_b_norms)}")',
        'if np.mean(lora_b_norms) < 1e-3:',
        '    print("⚠️  WARNING: lora_B norms tiny — DPO may not have trained meaningfully (POC bug)")',
        'else:',
        '    print("✓ lora_B norms healthy — DPO trained")',
    ]))
    cells.append(code([
        '# === RELOAD TEST: load saved LoRA into a separate model copy and verify base ≠ student ===',
        '# This is the test that nb35 POC failed.',
        'from peft import PeftModel',
        '',
        '# Save current model to Drive first (preserve trained weights for next phases)',
        '# Then reload as fresh PeftModel from saved adapter to verify save format',
        '',
        '# Method 1: same model, just swap adapters in/out',
        '# But simpler: use disable_adapter context to compare',
        '@torch.no_grad()',
        'def quick_gen(q, max_new=64):',
        '    msgs = [{"role":"user","content":q}]',
        '    txt = tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True, enable_thinking=True)',
        '    enc = tok(txt, return_tensors="pt").to(device)',
        '    out = model.generate(**enc, max_new_tokens=max_new, do_sample=False,',
        '                         pad_token_id=tok.pad_token_id or tok.eos_token_id)',
        '    return tok.decode(out[0, enc["input_ids"].shape[1]:], skip_special_tokens=True).strip()',
        '',
        'q_test = "Who invented the typewriter?"',
        'with model.disable_adapter():',
        '    a_base = quick_gen(q_test)',
        'a_stud = quick_gen(q_test)',
        '',
        'print(f"Base[:120]:    {a_base[:120]}")',
        'print(f"Student[:120]: {a_stud[:120]}")',
        'print(f"Identical? {a_base == a_stud}")',
        '',
        'if a_base == a_stud:',
        '    print("⚠️  WARNING: base == student. LoRA effect imperceptible at temp=0 greedy.")',
        '    print("    Try: gen with temp=0.7 to amplify any LoRA delta.")',
        '    a_base_07 = ""',
        '    a_stud_07 = ""',
        '    with torch.no_grad():',
        '        with model.disable_adapter():',
        '            torch.manual_seed(42)',
        '            a_base_07 = quick_gen(q_test).replace("\\n", " ")[:200]',
        '        torch.manual_seed(42)',
        '        a_stud_07 = quick_gen(q_test).replace("\\n", " ")[:200]',
        '    print(f"  Base@temp=0.7:    {a_base_07[:120]}")',
        '    print(f"  Student@temp=0.7: {a_stud_07[:120]}")',
        '',
        '(OUT / "_phase7_done.txt").write_text(f"ts={time.time()}, identical_at_greedy={a_base == a_stud}")',
        'api.upload_folder(folder_path=str(OUT), repo_id=CFG["output_repo"],',
        '                  repo_type="dataset", token=HF_TOKEN,',
        '                  commit_message="Phase 7: LoRA save verified",',
        '                  allow_patterns=["lora_final/*", "_phase7_done.txt"])',
        'print("✓ Phase 7 complete")',
    ]))

    # ============================================================
    # PHASE 8 — Eval base vs student
    # ============================================================
    cells.append(md(['## Phase 8 — Eval base vs student on 100 held-out queries (~3h)']))
    cells.append(code([
        'eval_path = OUT / "eval_results.csv"',
        '',
        'sqa_e = load_dataset("basicv8vc/SimpleQA", split="test").shuffle(seed=99).select(range(CFG["eval_n_simpleqa"]))',
        'gsm_e = load_dataset("openai/gsm8k", "main", split="test").shuffle(seed=99).select(range(CFG["eval_n_gsm8k"]))',
        'eval_qs = ([(ex["problem"],"simpleqa", f"sqa_e_{i}") for i, ex in enumerate(sqa_e)] +',
        '           [(ex["question"],"gsm8k", f"gsm_e_{i}") for i, ex in enumerate(gsm_e)])',
        '',
        '# Resume',
        'if eval_path.exists():',
        '    df_e = pd.read_csv(eval_path)',
        '    done_eval = set(df_e["id"].tolist())',
        '    print(f"Resume: {len(df_e)} eval rows already done")',
        'else:',
        '    df_e = pd.DataFrame()',
        '    done_eval = set()',
        '',
        'remaining_eval = [(q, src, eid) for (q, src, eid) in eval_qs if eid not in done_eval]',
        'print(f"Remaining: {len(remaining_eval)}/{len(eval_qs)}")',
        '',
        'for q, src, eid in tqdm(remaining_eval, desc="eval"):',
        '    with model.disable_adapter():',
        '        ans_b = gen_one(q, temp=0.0)',
        '    ans_s = gen_one(q, temp=0.0)',
        '    rb = combined_reward(q, ans_b)',
        '    rs_ = combined_reward(q, ans_s)',
        '    new_row = {"id": eid, "q": q[:100], "src": src,',
        '               "fg_base": rb["fg"], "fg_stud": rs_["fg"],',
        '               "rg_base": rb["rg"], "rg_stud": rs_["rg"],',
        '               "comb_base": rb["combined"], "comb_stud": rs_["combined"],',
        '               "ans_base_len": len(ans_b), "ans_stud_len": len(ans_s)}',
        '    df_e = pd.concat([df_e, pd.DataFrame([new_row])], ignore_index=True)',
        '    if len(df_e) % 10 == 0:',
        '        df_e.to_csv(eval_path, index=False)',
        '',
        'df_e.to_csv(eval_path, index=False)',
        '',
        'print("\\n" + "="*60)',
        'print("  Eval Verdict — Phase 8")',
        'print("="*60)',
        'for src in ["simpleqa","gsm8k"]:',
        '    sub = df_e[df_e.src==src]',
        '    fg_red = (sub["fg_base"].mean()-sub["fg_stud"].mean())/sub["fg_base"].mean()*100',
        '    rg_sub = sub.dropna(subset=["rg_base","rg_stud"])',
        '    rg_red = ((rg_sub["rg_base"].mean()-rg_sub["rg_stud"].mean())/rg_sub["rg_base"].mean()*100',
        '              if len(rg_sub)>0 else float("nan"))',
        '    comb_red = (sub["comb_base"].mean()-sub["comb_stud"].mean())/sub["comb_base"].mean()*100',
        '    print(f"  {src:10s}: FG -{fg_red:.1f}% · RG -{rg_red:.1f}% · combined -{comb_red:.1f}%")',
        '    print(f"             FG base {sub[\'fg_base\'].mean():.3f} → student {sub[\'fg_stud\'].mean():.3f}")',
        'print("="*60)',
        '',
        'api.upload_folder(folder_path=str(OUT), repo_id=CFG["output_repo"],',
        '                  repo_type="dataset", token=HF_TOKEN,',
        '                  commit_message="Phase 8: eval complete",',
        '                  allow_patterns=["eval_results.csv", "_phase8_done.txt"])',
        '(OUT / "_phase8_done.txt").write_text(f"ts={time.time()}, n_eval={len(df_e)}")',
        'print("✓ Phase 8 complete")',
    ]))

    # ============================================================
    # PHASE 9 — Anti-Goodhart
    # ============================================================
    cells.append(md([
        '## Phase 9 — Anti-Goodhart fresh-probe validation (~6h, MANDATORY)',
        '',
        'The 4-quadrant verdict that distinguishes real reduction from probe evasion.',
        '',
        '| Halu rate change | Original probe AUROC student | Fresh probe AUROC student | Interpretation |',
        '|---|---|---|---|',
        '| ↓ caiu | qualquer | **≥ 0.80** | ✅ Real improvement |',
        '| → mantém | ↓ caiu | ↓ caiu | ❌ Goodhart confirmed |',
        '| → mantém | ↓ caiu | ≥ 0.80 | 🟡 Partial evasion (signal moved direction) |',
        '| ↓ caiu | qualquer | < 0.80 | 🟠 Signal eroded |',
    ]))
    cells.append(code([
        'NUMBER_RE = re.compile(r"-?\\d+(?:[.,]\\d+)?")',
        '',
        'def normalize_answer(s):',
        '    return "".join(c.lower() for c in str(s) if c.isalnum() or c.isspace()).strip()',
        '',
        'def grade_gsm8k(gen, gold):',
        '    if "####" in gold:',
        '        try: gold_num = float(gold.split("####")[-1].strip().replace(",",""))',
        '        except: return False',
        '    else:',
        '        nums = NUMBER_RE.findall(gold)',
        '        if not nums: return False',
        '        gold_num = float(nums[-1].replace(",",""))',
        '    nums = NUMBER_RE.findall(gen)',
        '    if not nums: return False',
        '    try: gen_num = float(nums[-1].replace(",",""))',
        '    except: return False',
        '    return abs(gen_num - gold_num) < 1e-2',
        '',
        '@torch.no_grad()',
        'def capture_l31(question, answer):',
        '    enc = tok(f"Q: {question}\\nA: {answer}", return_tensors="pt", truncation=True, max_length=2048).to(device)',
        '    n = int(enc["attention_mask"].sum().item())',
        '    with model.disable_adapter():',
        '        _ = model(**enc)',
        '    return ml_hook.pop(31)[0, n-1].float().cpu().numpy()',
        '',
        '@torch.no_grad()',
        'def capture_l55(question, full_answer):',
        '    chat = [{"role":"user","content":question}]',
        '    prefix = tok.apply_chat_template(chat, tokenize=False, add_generation_prompt=True, enable_thinking=True)',
        '    enc = tok(prefix + full_answer, return_tensors="pt", truncation=True, max_length=4096).to(device)',
        '    ids = enc["input_ids"][0].tolist()',
        '    op = next((i for i,t in enumerate(ids) if t == THINK_OPEN_ID), None)',
        '    cl = next((i for i,t in enumerate(ids) if t == THINK_CLOSE_ID), None)',
        '    if op is None or cl is None or cl <= op + 5: return None',
        '    mid = (op + cl) // 2',
        '    with model.disable_adapter():',
        '        _ = model(**enc)',
        '    return ml_hook.pop(55)[0, mid].float().cpu().numpy()',
        '',
        'sqa_fresh = load_dataset("basicv8vc/SimpleQA", split="test").shuffle(seed=777).select(range(CFG["antigoodhart_n_simpleqa"]))',
        'gsm_fresh = load_dataset("openai/gsm8k", "main", split="test").shuffle(seed=777).select(range(CFG["antigoodhart_n_gsm8k"]))',
        '',
        'def collect(eval_set, label_fn, ques_key, ans_key, src, mode):',
        '    out = {"fg":{"X":[],"y":[]}, "rg":{"X":[],"y":[]}}',
        '    for ex in tqdm(eval_set, desc=f"{src}/{mode}"):',
        '        q = ex[ques_key]; gold = ex[ans_key]',
        '        if isinstance(gold, list) and gold: gold = gold[0]',
        '        if mode == "base":',
        '            with model.disable_adapter():',
        '                ans = gen_one(q, temp=0.0)',
        '        else:',
        '            ans = gen_one(q, temp=0.0)',
        '        halu = int(not label_fn(ans, gold))',
        '        h31 = capture_l31(q, ans)',
        '        out["fg"]["X"].append(h31); out["fg"]["y"].append(halu)',
        '        h55 = capture_l55(q, ans)',
        '        if h55 is not None:',
        '            out["rg"]["X"].append(h55); out["rg"]["y"].append(halu)',
        '    return out',
        '',
        'samples_base    = {"fg":{"X":[],"y":[]}, "rg":{"X":[],"y":[]}}',
        'samples_student = {"fg":{"X":[],"y":[]}, "rg":{"X":[],"y":[]}}',
        '',
        'for mode, dst in [("base", samples_base), ("student", samples_student)]:',
        '    sqa_s = collect(sqa_fresh, lambda a,g: normalize_answer(g) in normalize_answer(a),',
        '                    "problem","answer","simpleqa", mode)',
        '    gsm_s = collect(gsm_fresh, grade_gsm8k, "question","answer","gsm8k", mode)',
        '    for k in ["fg","rg"]:',
        '        dst[k]["X"].extend(sqa_s[k]["X"] + gsm_s[k]["X"])',
        '        dst[k]["y"].extend(sqa_s[k]["y"] + gsm_s[k]["y"])',
        '',
        '# Save activations to Drive',
        'np.savez_compressed(OUT / "fresh_activations_base.npz",',
        '    X_fg=np.array(samples_base["fg"]["X"]), y_fg=np.array(samples_base["fg"]["y"]),',
        '    X_rg=np.array(samples_base["rg"]["X"]) if samples_base["rg"]["X"] else np.array([]),',
        '    y_rg=np.array(samples_base["rg"]["y"]) if samples_base["rg"]["y"] else np.array([]))',
        'np.savez_compressed(OUT / "fresh_activations_student.npz",',
        '    X_fg=np.array(samples_student["fg"]["X"]), y_fg=np.array(samples_student["fg"]["y"]),',
        '    X_rg=np.array(samples_student["rg"]["X"]) if samples_student["rg"]["X"] else np.array([]),',
        '    y_rg=np.array(samples_student["rg"]["y"]) if samples_student["rg"]["y"] else np.array([]))',
        'print("✓ Activations persisted to Drive")',
    ]))
    cells.append(code([
        '# Train fresh probes + compare',
        'def fresh_probe_auc(X, y, name):',
        '    X, y = np.array(X), np.array(y)',
        '    if len(np.unique(y)) < 2 or sum(y) < 5 or sum(1-y) < 5:',
        '        return None, len(y), float(y.mean())',
        '    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)',
        '    sc = StandardScaler().fit(X_tr)',
        '    cv = min(5, sum(y_tr).item(), sum(1-y_tr).item())',
        '    clf = LogisticRegressionCV(Cs=[0.001,0.01,0.1,1,10], cv=cv, penalty="l2",',
        '                               solver="lbfgs", max_iter=2000, scoring="roc_auc"',
        '                               ).fit(sc.transform(X_tr), y_tr)',
        '    return float(roc_auc_score(y_te, clf.predict_proba(sc.transform(X_te))[:,1])), len(y), float(y.mean())',
        '',
        'def orig_auc(X, y, probe, scaler):',
        '    X, y = np.array(X), np.array(y)',
        '    if len(np.unique(y)) < 2: return None',
        '    pos_idx = list(probe.classes_).index(1)',
        '    return float(roc_auc_score(y, probe.predict_proba(scaler.transform(X))[:, pos_idx]))',
        '',
        'verdict = {}',
        'for layer_name, samples_b, samples_s, probe, scaler in [',
        '    ("L31_FG", samples_base["fg"], samples_student["fg"], fg_probe, fg_scaler),',
        '    ("L55_RG", samples_base["rg"], samples_student["rg"], rg_probe, rg_scaler),',
        ']:',
        '    halu_b = float(np.mean(samples_b["y"])) if samples_b["y"] else float("nan")',
        '    halu_s = float(np.mean(samples_s["y"])) if samples_s["y"] else float("nan")',
        '    auc_orig_b = orig_auc(samples_b["X"], samples_b["y"], probe, scaler) if samples_b["X"] else None',
        '    auc_orig_s = orig_auc(samples_s["X"], samples_s["y"], probe, scaler) if samples_s["X"] else None',
        '    auc_fresh, n, halu_check = fresh_probe_auc(samples_s["X"], samples_s["y"], layer_name)',
        '    print(f"\\n{layer_name}:")',
        '    print(f"  halu rate base→student: {halu_b*100:.1f}% → {halu_s*100:.1f}% (Δ {(halu_s-halu_b)*100:+.1f}pp)")',
        '    print(f"  orig probe AUROC: base {auc_orig_b} → student {auc_orig_s}")',
        '    print(f"  FRESH probe AUROC: {auc_fresh} (n={n})")',
        '    verdict[layer_name] = {',
        '        "halu_b": halu_b, "halu_s": halu_s,',
        '        "auc_orig_b": auc_orig_b, "auc_orig_s": auc_orig_s,',
        '        "auc_fresh_s": auc_fresh, "n": n',
        '    }',
        '',
        'def diagnose(d):',
        '    if any(d[k] is None for k in ["auc_orig_s", "auc_fresh_s"]): return "⚠️  insufficient data"',
        '    halu_dropped = d["halu_s"] < d["halu_b"] - 0.03',
        '    orig_dropped = d["auc_orig_s"] < 0.65',
        '    fresh_high   = d["auc_fresh_s"] >= 0.80',
        '    if halu_dropped and fresh_high:           return "✅ REAL IMPROVEMENT"',
        '    if not halu_dropped and orig_dropped and not fresh_high: return "❌ GOODHART CONFIRMED"',
        '    if not halu_dropped and orig_dropped and fresh_high:     return "🟡 PARTIAL EVASION"',
        '    if halu_dropped and not fresh_high:       return "🟠 SIGNAL ERODED"',
        '    if not halu_dropped and not orig_dropped: return "🟢 NO CHANGE"',
        '    return "?  mixed signals"',
        '',
        'print("\\n" + "="*72)',
        'print("  Anti-Goodhart 4-quadrant verdict")',
        'print("="*72)',
        'for k, d in verdict.items():',
        '    print(f"  {k}: {diagnose(d)}")',
        '    verdict[k]["interpretation"] = diagnose(d)',
        'print("="*72)',
        '',
        '(OUT / "antigoodhart_verdict.json").write_text(json.dumps(verdict, indent=2, default=str))',
        '',
        'api.upload_folder(folder_path=str(OUT), repo_id=CFG["output_repo"],',
        '                  repo_type="dataset", token=HF_TOKEN,',
        '                  commit_message="Phase 9: anti-Goodhart verdict",',
        '                  allow_patterns=["fresh_activations_*.npz", "antigoodhart_verdict.json", "_phase9_done.txt"])',
        '(OUT / "_phase9_done.txt").write_text(f"ts={time.time()}")',
        'print("✓ Phase 9 complete")',
    ]))

    # ============================================================
    # PHASE 10 — Final summary + plots
    # ============================================================
    cells.append(md(['## Phase 10 — Final summary + plots']))
    cells.append(code([
        '# Compile final verdict',
        'final = {',
        '    "date": time.strftime("%Y-%m-%d"),',
        '    "config": {k: v for k, v in CFG.items() if k != "output_repo"},',
        '    "phase5_build_pairs": {',
        '        "n_pairs": len(pairs),',
        '        "mean_combined_gap": float(df_t["combined_gap"].mean()),',
        '        "has_think_rate": float(df_t["has_think_rate"].mean()),',
        '        "fg_rg_pearson": float(np.corrcoef(df_t.dropna(subset=["rg_best"])["fg_best"],',
        '                                          df_t.dropna(subset=["rg_best"])["rg_best"])[0,1])',
        '                          if len(df_t.dropna(subset=["rg_best"])) > 5 else None,',
        '    },',
        '    "phase6_dpo": {',
        '        "epochs": CFG["num_train_epochs"],',
        '        "lora_b_norm_mean": float(np.mean([v.float().norm().item() for k,v in saved.items() if "lora_B" in k])),',
        '    },',
        '    "phase8_eval": {',
        '        "n": len(df_e),',
        '        "fg_simpleqa_reduction_pct": float((df_e[df_e.src=="simpleqa"]["fg_base"].mean() - df_e[df_e.src=="simpleqa"]["fg_stud"].mean()) / df_e[df_e.src=="simpleqa"]["fg_base"].mean() * 100),',
        '        "fg_gsm8k_reduction_pct":    float((df_e[df_e.src=="gsm8k"]["fg_base"].mean()    - df_e[df_e.src=="gsm8k"]["fg_stud"].mean())    / df_e[df_e.src=="gsm8k"]["fg_base"].mean() * 100),',
        '    },',
        '    "phase9_antigoodhart": verdict,',
        '}',
        '(OUT / "FINAL_VERDICT.json").write_text(json.dumps(final, indent=2, default=str))',
        'print("\\n=== FINAL VERDICT ===")',
        'print(json.dumps(final, indent=2, default=str))',
        '',
        '# Plots',
        'plots = OUT / "plots"; plots.mkdir(exist_ok=True)',
        '',
        '# Loss curve',
        'try:',
        '    log_history = trainer.state.log_history',
        '    losses = [(h["step"], h["loss"]) for h in log_history if "loss" in h]',
        '    if losses:',
        '        steps, vals = zip(*losses)',
        '        fig, ax = plt.subplots(figsize=(8,4))',
        '        ax.plot(steps, vals, marker="o")',
        '        ax.axhline(np.log(2), color="r", linestyle="--", alpha=0.5, label="ln(2) random baseline")',
        '        ax.set_xlabel("Step"); ax.set_ylabel("DPO loss")',
        '        ax.set_title("DPO training loss")',
        '        ax.legend()',
        '        fig.tight_layout()',
        '        fig.savefig(plots / "dpo_loss.png", dpi=150)',
        '        plt.close()',
        'except Exception as e:',
        '    print(f"loss plot failed: {e}")',
        '',
        '# Eval before/after bar chart',
        'fig, ax = plt.subplots(figsize=(9,5))',
        'srcs = ["simpleqa", "gsm8k"]',
        'fg_b = [df_e[df_e.src==s]["fg_base"].mean() for s in srcs]',
        'fg_s = [df_e[df_e.src==s]["fg_stud"].mean() for s in srcs]',
        'x = np.arange(len(srcs))',
        'ax.bar(x-0.2, fg_b, width=0.4, color="#94a3b8", label="Base")',
        'ax.bar(x+0.2, fg_s, width=0.4, color="#6366f1", label="Student (after DPO)")',
        'ax.set_xticks(x); ax.set_xticklabels(srcs)',
        'ax.set_ylabel("FabricationGuard probe score (P(halu))")',
        'ax.set_title("Multi-Probe DPO — base vs student probe scores")',
        'ax.legend()',
        'for i, (b, s) in enumerate(zip(fg_b, fg_s)):',
        '    delta = (b - s) / b * 100',
        '    ax.text(i, max(b, s) + 0.02, f"-{delta:.1f}%", ha="center", fontweight="bold")',
        'fig.tight_layout()',
        'fig.savefig(plots / "fg_before_after.png", dpi=150)',
        'plt.close()',
        '',
        'api.upload_folder(folder_path=str(OUT), repo_id=CFG["output_repo"],',
        '                  repo_type="dataset", token=HF_TOKEN,',
        '                  commit_message=f"Phase 10 final: full run @ {time.strftime(\'%Y-%m-%d %H:%M\')}")',
        '(OUT / "_phase10_done.txt").write_text(f"ts={time.time()}")',
        'print(f"\\n✅ FULL RUN COMPLETE — https://huggingface.co/datasets/{CFG[\'output_repo\']}")',
    ]))

    cells.append(md([
        '## Honest reading',
        '',
        'After Phase 9 finishes, the verdict tells the truth:',
        '',
        '- **L31_FG / L55_RG = ✅ REAL IMPROVEMENT**: shipping news. First OSS multi-probe DPO with anti-Goodhart validation on 27B+ open weights. Goodfire RLFR territory.',
        '',
        '- **❌ GOODHART CONFIRMED**: model evades probe direction. Result invalid — re-train with rotated probe or add more orthogonal probes.',
        '',
        '- **🟡 PARTIAL EVASION**: signal still detectable but moved off original direction. Honest mid-result. Update probe + re-run.',
        '',
        '- **🟠 SIGNAL ERODED**: improvement real but probe-relevant signal weakened. Classifier capability hurt. Lower DPO LR or smaller r.',
        '',
        '- **🟢 NO CHANGE**: training did not move the needle. More compute or different reward needed. POC nb35 hit this.',
        '',
        'Whatever the result, register honestly on ProbeBench. Negative results are first-class.',
    ]))

    write_nb(cells, NOTEBOOKS_DIR / '37_multiprobe_dpo_full_run.ipynb')


if __name__ == "__main__":
    print("=== Building nb 37 ===")
    build_nb37()
    print("✓ Done")
